name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'quick-fix'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'maintenance'
      - 'maintain'
      - 'cleanup'
      - 'dependencies'
  # Default label used by Dependabot
  - title: '📦 Dependency updates'
    label: dependencies
  - title: '📝 Documentation updates'
    label:
      - 'documentation'
      - 'docs'
  - title: '🚦 Tests'
    labels:
      - test
      - tests

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '@dependabot-preview'
    replace: '@dependabot'
