name: Update Security Hub schema

on: [pull_request]

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Github CLI
        env:
          GH_REPO: xen0l/action-pr-test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -OL https://github.com/cli/cli/releases/download/v1.4.0/gh_1.4.0_linux_amd64.tar.gz
          tar xf gh_1.4.0_linux_amd64.tar.gz
          cp gh_1.4.0_linux_amd64/bin/gh ~
          chmod +x ~/gh
          gh pr list
          
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Modify README.md
        run: |
          echo $(date %s) >> README.md
          git add README.md
          git commit -m "Schema update $(date)"
          gh pr create

